services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: false

  Lp\MatterhornImport\:
    resource: '../src/*'
    exclude:
      - '../src/DTO/'

  Lp\MatterhornImport\Contract\SourceInterface:
    alias: Lp\MatterhornImport\Source\MatterhornXmlSource

  Lp\MatterhornImport\Contract\ProductMapperInterface:
    alias: Lp\MatterhornImport\Mapper\MatterhornProductMapper

  Lp\MatterhornImport\Contract\SizeResolverInterface:
    alias: Lp\MatterhornImport\Matterhorn\MatterhornSizeResolver
