<?php
namespace Lp\MatterhornImport\Import;

use Lp\MatterhornImport\Contract\OutOfFeedPolicyInterface; use Lp\MatterhornImport\Repository\ErrorRepository; use Lp\MatterhornImport\Repository\MappingRepository; use Lp\MatterhornImport\Repository\RunRepository; use Lp\MatterhornImport\Repository\SnapshotRepository; use Lp\MatterhornImport\Util\DatabaseSafety; use Lp\MatterhornImport\Util\ExecutionBudget; use Lp\MatterhornImport\Util\RunFailureRecorder; use Lp\MatterhornImport\Util\TransientDatabaseFailure;

final class RemoveStage
{
    private const SAVEPOINT='matterhorn_remove_item'; private const DEFAULT_MAX_REMOVE_PERCENT=25;
    public function __construct(private OutOfFeedPolicyInterface $outOfFeedPolicy,private RunRepository $runs,private SnapshotRepository $snapshots,private MappingRepository $mapping,private ErrorRepository $errors,private DatabaseSafety $safety,private RunFailureRecorder $failureRecorder,private ExecutionBudget $budget){}
    public function plan(int$runId,int$shopId,string$source):array{$run=$this->runs->assertContext($runId,$shopId,$source);$this->assertRunnable($run);$mapped=$this->mapping->countInFeedSource($shopId,$source);$candidates=$mapped>0?$this->snapshots->countRemoved($runId,$shopId,$source):0;$max=$this->maxRemovePercent($shopId);$percent=$mapped>0?($candidates*100.0)/$mapped:0.0;return['mapped'=>$mapped,'candidates'=>$candidates,'percent'=>$percent,'max_percent'=>$max,'safe'=>$mapped<=0||$candidates<=0||$percent<=$max];}
    public function run(int$runId,int$shopId,string$source,int$batch=500,int$maxItems=0,int$timeLimitSeconds=0):bool
    {$this->safety->assertTransactionalCore();$plan=$this->plan($runId,$shopId,$source);$this->budget->start($maxItems,$timeLimitSeconds);
        try{$this->assertRemovalPlanSafe($plan);$this->runs->resume($runId);$this->runs->resetStageFailureCounter($runId,'remove');$this->runs->stage($runId,'remove','running');$cursor=0;$failures=0;$paused=false;$batch=max(1,min(2000,$batch));
            while(!$this->budget->shouldStop()&&($rows=$this->snapshots->removedRows($runId,$shopId,$source,$cursor,$batch))!==[]){$db=\Db::getInstance();if(!$db->execute('START TRANSACTION')){throw new \RuntimeException('Could not start REMOVE batch transaction');}$done=0;$batchFailures=0;
                try{foreach($rows as$row){if($this->budget->shouldStop()){$paused=true;break;}$productId=(int)$row['id_product'];$cursor=$productId;$this->beginItemSavepoint($db);
                        try{$this->outOfFeedPolicy->apply($productId,$shopId);$this->restoreItemSavepointAfterExternalCommit($db);$this->mapping->markOutOfFeed($shopId,$source,(string)$row['source_key'],$runId);if(!$db->execute('RELEASE SAVEPOINT '.self::SAVEPOINT)){throw new \RuntimeException('Could not release REMOVE item savepoint');}$done++;$this->budget->markItem();}
                        catch(\Throwable$itemError){if(TransientDatabaseFailure::isRetryable($itemError)){throw$itemError;}$this->rollbackItemSavepoint($db,$itemError);$batchFailures++;$this->budget->markItem();$this->errors->add($runId,'remove',(string)($row['source_key']??''),$itemError);}}
                    if($done>0){$this->runs->increment($runId,'remove_done',$done);}if($batchFailures>0){$this->runs->increment($runId,'remove_failed',$batchFailures);}if(!$db->execute('COMMIT')){throw new \RuntimeException('Could not commit REMOVE batch');}}
                catch(\Throwable$batchError){$db->execute('ROLLBACK');throw$batchError;}$failures+=$batchFailures;if($paused||$this->budget->shouldStop()){$paused=true;break;}}
            if($failures>0){throw new \RuntimeException('REMOVE completed with '.$failures.' failed item(s); retry required');}if($paused||$this->budget->shouldStop()){$this->runs->stage($runId,'remove','paused');$this->runs->finish($runId,'paused');return false;}$this->runs->stage($runId,'remove','completed');$this->runs->finish($runId,'completed');return true;
        }catch(\Throwable$e){$this->failureRecorder->record($runId,'remove',$e);throw$e;}}
    private function beginItemSavepoint(\Db$db):void{if(!$this->transactionIsActive($db)&&!$db->execute('START TRANSACTION')){throw new \RuntimeException('Could not restore REMOVE transaction');}if(!$db->execute('SAVEPOINT '.self::SAVEPOINT)){throw new \RuntimeException('Could not create REMOVE item savepoint');}}
    private function restoreItemSavepointAfterExternalCommit(\Db$db):void{if($this->transactionIsActive($db)){return;}if(!$db->execute('START TRANSACTION')||!$db->execute('SAVEPOINT '.self::SAVEPOINT)){throw new \RuntimeException('Could not restore REMOVE transaction after PrestaShop commit');}}
    private function rollbackItemSavepoint(\Db$db,\Throwable$cause):void{if(!$this->transactionIsActive($db)){return;}if(!$db->execute('ROLLBACK TO SAVEPOINT '.self::SAVEPOINT)){$db->execute('ROLLBACK');throw new \RuntimeException('Could not rollback REMOVE savepoint',0,$cause);}if(!$db->execute('RELEASE SAVEPOINT '.self::SAVEPOINT)){throw new \RuntimeException('Could not release REMOVE rollback savepoint',0,$cause);}}
    private function transactionIsActive(\Db$db):bool{$value=$db->getValue('SELECT @@session.in_transaction', false);if($value===false){throw new \RuntimeException('Could not inspect REMOVE transaction state');}return(int)$value===1;}
    private function assertRunnable(array$run):void{if((string)$run['read_status']!=='completed'||(string)$run['import_status']!=='completed'||(string)$run['update_status']!=='completed'||(int)$run['source_valid']===0){throw new \RuntimeException('REMOVE blocked: previous stages or source sanity check incomplete');}if((string)$run['remove_status']==='completed'){throw new \RuntimeException('REMOVE is already completed for this run');}}
    private function assertRemovalPlanSafe(array$plan):void{if($plan['safe']){return;}throw new \RuntimeException(sprintf('REMOVE safety guard blocked %d of %d in-feed products (%.2f%%); configured maximum is %d%%',$plan['candidates'],$plan['mapped'],$plan['percent'],$plan['max_percent']));}
    private function maxRemovePercent(int$shopId):int{$configured=(int)\Configuration::get('MATTERHORNIMPORT_MAX_REMOVE_PERCENT',null,null,$shopId);return$configured>0?max(1,min(100,$configured)):self::DEFAULT_MAX_REMOVE_PERCENT;}
}
